
export const mockedOptions = [
    {label: 'Apple', value: 'apple'},
    {label: 'Banana', value: 'banana'},
    {label: 'Cherry', value: 'cherry'},
    {label: 'Durian', value: 'durian'},
    {label: 'Elderberry', value: 'elderberry'},
    {label: 'Fig', value: 'fig'},
    {label: 'Grape', value: 'grape'},
    {label: 'Honeydew', value: 'honeydew'},
    {label: 'Iced Melon', value: 'iced melon'},
    {label: 'Jackfruit', value: 'jackfruit'},
    {label: 'Kiwi', value: 'kiwi'},
    {label: 'Lemon', value: 'lemon'},
    {label: 'Mango', value: 'mango'},
    {label: 'Nectarine', value: 'nectarine'},
    {label: 'Orange', value: 'orange'},
    {label: 'Pineapple', value: 'pineapple'},
    {label: 'Quince', value: 'quince'},
    {label: 'Raspberry', value: 'raspberry'},
    {label: 'Strawberry', value: 'strawberry'},
    {label: 'Tangerine', value: 'tangerine'},
    {label: 'Ugli Fruit', value: 'ugli fruit'},
    {label: 'Vanilla Bean', value: 'vanilla bean'},
    {label: 'Watermelon', value: 'watermelon'},
    {label: 'Xigua', value: 'xigua'},
    {label: 'Yellow Watermelon', value: 'yellow watermelon'},
    {label: 'Zucchini', value: 'zucchini'},
    {label: 'Apricot', value: 'apricot'},
    {label: 'Blueberry', value: 'blueberry'},
    {label: 'Cantaloupe', value: 'cantaloupe'},
    {label: 'Dragonfruit', value: 'dragonfruit'},
    {label: 'Eggplant', value: 'eggplant'},
    {label: 'Fuyu Persimmon', value: 'fuyu persimmon'},
    {label: 'Grapefruit', value: 'grapefruit'},
    {label: 'Huckleberry', value: 'huckleberry'},
    {label: 'Jujube', value: 'jujube'},
    {label: 'Kumquat', value: 'kumquat'},
    {label: 'Lime', value: 'lime'},
    {label: 'Navel Orange', value: 'navel orange'},
    {label: 'Peach', value: 'peach'},
    {label: 'Rambutan', value: 'rambutan'},
    {label: 'Starfruit', value: 'starfruit'},
    {label: 'Tomato', value: 'tomato'},
    {label: 'Ugni', value: 'ugni'},
    {label: 'Victoria Plum', value: 'victoria plum'},
    {label: 'White Grape', value: 'white grape'},
    {label: 'Yuzu', value: 'yuzu'}
]
